install:
  - curl http://static.rust-lang.org/cargo-dist/cargo-nightly-linux.tar.gz |
      sudo tar --strip-components 1 -C /usr -xzf -
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - make deps
script:
  - rustc -v
  - make test
env:
  - LD_LIBRARY_PATH=/usr/local/lib
